---
configs:
    general:
        public_ip: '192.168.1.117'
        memory: 2048
        mysql_root_pwd: root
    services:
        phpmyadmin: true
        xdebug: true
        nodejs: true
        redis: true
        memcached: true
        mailutils: true
        elasticsearch: true
